// tp/angular-app/src/app/todo/todo.component.ts
import { Component, Input, OnInit } from "@angular/core";

@Component({
  selector: "app-todo",
  templateUrl: "./todo.component.html",
})
export class TodoComponent implements OnInit {
  @Input() completed = false;
  @Input() title = "";

  constructor() {}

  ngOnInit(): void {}
}

<input type="checkbox" [checked]="completed" />
{{title}}

// tp/react-app/src/TodoComponent.jsx
import React from "react";


export function TodoComponent(props) {
  // return React.createElement("div", {}, [
  //   React.createElement("input", {
  //     type: "checkbox",
  //     checked: props.completed
  //   }),
  //   props.title
  // ]);
  return (
    <div>
      <label>
        <input
          type="checkbox"
          checked={props.completed}
          onChange={e => props.onCompletedChange(e.target.checked)}
        />
        {props.title}
      </label>
    </div>
  );
}
